<body>
<small><h4 align="left">MAKE MUSIC NEW YORK, INC.</h4></small>  

<small><h4 align="left">TERMS AND CONDITIONS</h4></small>

<small><h4 align="left">PLEASE READ THE FOLLOWING TERMS AND CONDITIONS AND THE LIMITATION ON LIABILITY SET FORTH THEREIN CAREFULLY AND ACKNOWLEDGE THE TERMS AND CONDITIONS AFTER READING THEM BY CLICKING ON THE &quot;I AGREE&quot; BUTTON SET FORTH BELOW PRIOR TO USING THIS WEBSITE.</h4></small>
<small>
<p align="left">1.    All references to &quot;we&quot;, &quot;us&quot; and &quot;our&quot; below, are references to Make Music New York, Inc., a New York not-for-profit corporation (referred to herein as &quot;Make Music New York&quot;).  All references to &quot;you&quot; or &quot;your&quot; are references to anyone who registers by email, at <a href="http://www.makemusicny.org">www.makemusicny.org</a>, by telephone, or in person as a musician or performer, to provide a location for musicians or performers, or to otherwise participate in organizing and implementing any event that takes place in connection with Make Music New York (referred to herein as an &quot;Event&quot;).  Other capitalized terms used herein shall have the meanings set forth herein.</p>
<p align="left">2.    We are the voluntary resource coordinators of Make Music New York, a unique international music event that will take place on or about June 21, 2012 in New York City.  We match Make Music New York participants (e.g., musicians and performers) and volunteers (e.g., schools and other volunteers) with Make Music New York locations based on the information received via our website, by email, by telephone, or in person.  To be involved in Make Music New York or any Event, you must submit a completed registration form available at <a href="http://www.makemusicny.org/participate">www.makemusicny.org/participate</a> and agree to the terms and conditions you are now reading by clicking the &quot;I AGREE&quot; button set forth below.  Your participation in Make Music New York or any Event is expressly conditioned on your acknowledgment and acceptance of these terms and conditions by clicking the &quot;I AGREE&quot; button set forth below.  By clicking on the &quot;I AGREE&quot; button set forth below you agree to be legally bound by these terms and conditions by visiting our website and/or participating in Make Music New York or any Event.  If for any reason you fail to click on the &quot;I AGREE&quot; button set forth below you will still be deemed to agree to be legally bound by these terms and conditions by visiting our website and/or participating in Make Music New York or any Event.</p>
<p align="left">3.    We are not your partner, agent or representative and no aspect of our relationship with you creates any fiduciary, partnership, agency, employment, trust at law or other similar relationship for any purpose whatsoever.  You acknowledge and agree that we are not obliged to, nor will we make any, payment to you (royalty or otherwise) for your services as a Make Music New York musician or performer, your location for use as a Make Music New York venue, your equipment or your participation in any other respect in Make Music New York or any Event and will not reimburse you for any other costs or expenses associated with your participation in Make Music New York or any Event.</p>
<p align="left">4.    All registration forms completed by you (whether as a musician, performer or other participant in Make Music New York or any Event), including any information contained therein, will be our property, and you hereby assign to us any rights you may have therein.  You may provide us with &quot;Personal Information&quot; in the space provided when you complete the registration form (e.g. your name, address and telephone number), but doing so will be at your sole option.  We may use and communicate this Personal Information in the ways described in our privacy notice, a copy of which is available at http://makemusicny.org/privacy-policy/.  </p>
<p align="left">5.    You hereby authorize, and grant all necessary rights to, us and our assignees, licensees, servants, employees, agents, representatives and other persons acting in similar capacities to make recordings (both audio-visual and audio only) of your performances at an Event (referenced to herein as the &quot;Recordings&quot;).  We will use the Recordings for archival and promotional purposes and will not commercially release CDs or DVDs of the Recordings, unless we negotiate the relevant permissions and terms with you by separate agreement. We will own all rights (including copyright) throughout the world in perpetuity in the Recordings including the right to:  (a) broadcast and/or communicate the Recordings to the public via television broadcast (both during the performances and from the Recordings); (b) communicate the Recordings over the internet; (c) communicate the Recordings to the public on radio (both for simulcast with the Performances and for simulcast with any later broadcast or transmission of the Recordings); (d) communicate the Recordings via screens around the venue (if applicable); (e) include the Recordings or excerpts from the Recordings on a video, CD, DVD or in other promotional material related to Make Music New York; (f) synchronize the Recordings with any media for any purpose set out in this paragraph; (g) reproduce the Recordings and (h) for other similar purposes without your prior consent.  You will receive no payment for the uses of the Recordings.  You acknowledge that we have the right to use your name, professional name, photographs, image, likeness, biography and any other information provided by you to us for any purposes connected with Make Music New York (including promotional purposes) without your prior consent.</p>
<p align="left">6.    To the extent permitted by law, we expressly exclude all express or implied terms, conditions, agreements, covenants, statements, assurances, representations and warranties in relation to Make Music New York or any Event.  If any of the exclusions or limitations set out in these terms and conditions are declared illegal or void or if you claim that there has been a breach of a term, condition, statement, assurance, representation or warranty which cannot be excluded by these terms and conditions, to the extent permitted by law, our entire liability and your exclusive remedy is limited, at our discretion, to us supplying our services again in the manner provided from time to time on our website.  Nothing in these terms and conditions excludes, restricts or modifies any condition, warranty, right or remedy implied or imposed by statute or regulation if it cannot lawfully be excluded, restricted or modified.  </p>
<p align="left">7.    We have no involvement in the running or production of any Event.  Accordingly we do not accept any responsibility relating to the running or production of any Event, including:  (a) if any Event in which you participate is not capable of running as planned; (b) if any Event in which you participate is canceled or suspended; (c) for any problems or technical malfunction associated with any Event in which you participate; (d) if your services are canceled or suspended; or (e) for any injury, loss or damage incurred or caused by you in connection with your participation in Make Music New York or an Event.</p>
<p align="left">8.    To the extent permitted by law, in no event shall we be liable for, and you release us from any claim for, any direct, indirect, incidental, special, exemplary, punitive or consequential damages, or lost profit, goodwill or business however arising and on any theory of liability, including without limitation, contract or tort (including negligence or otherwise) in connection with your participation in Make Music New York or an Event even if we were aware of the possibility of such damage or if such damage was foreseeable.</p>
<p align="left">9.    You undertake and agree to indemnify us and our directors, officers, employees, agents and representatives and keep us and each of such other persons fully indemnified against all causes of action, suits, claims, demands, liability, damages, costs or expenses (including any and all of our legal fees on an indemnity basis) arising from or relating to:  (a) any breach of these terms and conditions or any express or implied representation, warranty, covenant or agreement by you; (b) any claim or action by any person arising out of any action or failure to act in connection with your participation in Make Music New York or an Event; and (c) any damage, injury or loss caused by or resulting from any willful act, bad faith, reckless disregard or negligence by you.</p>
<p align="left">10.    You agree that you will be liable for any direct or indirect loss or damage caused by you to any property of any Make Music New York venue, Make Music New York or any musician, performer, employee, agent or contractor of any Make Music New York venue or any other volunteer at any Make Music New York venue and for any unlawful or negligent act or omission by you.</p>
<p align="left">11.    The interpretation and enforcement of these terms and conditions will be governed by and construed in accordance with the laws of the State of New York.  You are deemed to agree to submit to the exclusive jurisdiction of the courts of the State of New York and to irrevocably and unconditionally waive any right to trial by jury in any action or proceeding arising from or in connection with these terms and conditions by visiting our website and/or participating in Make Music New York or any Event.</p>
<p align="left">12.    Our failure to require your performance of any provision of these terms and conditions will not affect our full right to require such performance at any time thereafter.  Our waiver of any provision in these terms and conditions will be a waiver of a particular application of the provision and not of the provision itself.  If any of these terms and conditions are found by any court or other competent authority to be invalid, illegal, unlawful or unenforceable, then the remainder of these terms and conditions shall continue to be valid and enforceable to the fullest extent permitted by law.  In such event, we will be entitled to amend or replace the provision that is held to be invalid, illegal, unlawful or unenforceable with one that is valid, legal, lawful and enforceable and which achieves, to the extent possible, our original objectives and intent as reflected in the original provision.</p>
<p align="left">13.    Any modifications to these terms and conditions will be posted on the Make Music New York website at <a href="http://www.makemusicny.org/participate">www.makemusicny.org/participate</a>. You will be bound by the version of the terms and conditions in existence at the time you register to participate in Make Music New York or any Event.  Your continued participation in Make Music New York or any Event after any modifications to these terms and conditions shall constitute your acceptance of the modified terms and conditions.</p>


<p align="left">If you have any questions regarding these terms and conditions, please contact <a href="mailto:makemusicny@gmail.com">makemusicny@gmail.com</a>.</p>

<p align="left">Effective Date: March 8, 2012</p></small>
</body>
<!--
<body>
<small><h4 align="left">MAKE MUSIC NEW YORK:<br> LIMITATION OF LIABILITY</h4></small>
<small><p align="left">1. All references to &quot;we&quot;, &quot;us&quot; and &quot;our&quot; below, are references to &quot;Make Music New York, Inc.&quot;. All references to &quot;you&quot; or &quot;your&quot; are references to anyone who registers by email, at <a href="http://www.makemusicny.org">www.makemusicny.org</a>, at <a href="http://www.timeoutnewyork.com/makemusic">www.timeoutnewyork.com/makemusic</a>, by phone, or in person as a musician or performer, or to provide a location for musicians or performers.</p>
<p align="left">2. We are the voluntary resource coordinators of &quot;Make Music New York,&quot; a unique international music event that will take place on June 21st, 2010 in New York City. We match Make Music New York volunteers (e.g. musicians and performers, schools and other volunteers) with Make Music New York locations based on the information received via our website, by email, by phone, or in person. To be involved in Make Music New York, you must agree to the document you are now reading, available at www.makemusicny.org.</p>
<p align="left">3. We are not your partner, agent or representative and no aspect of our relationship with you creates any agency, partnership, employment or trust at law for any purpose whatsoever. We are not obliged to, nor will we make any, payment to you (royalty or otherwise) for your services as a Make Music New York musician or performer or for your location for use as a Make Music New York venue, equipment or other costs.</p>
<p align="left">4. All registration forms will be our property. You may provide us with &quot;Personal Information&quot; when you complete the registration form (e.g. your name, age, address and phone number). We may use and communicate this Personal Information in the ways described in our privacy policy, a copy of which is available at www.makemusicny.org. </p>
<p align="left">5. You authorize us and our assignees, licensees, servants, employees and/or agents to make recordings (both audio-visual and audio only) of your performances (&quot;Recordings&quot;). We will only use the Recordings for archival and promotional purposes and we will not commercially release CDs or DVDs of the Recordings, unless we negotiate the relevant permissions and terms with you by separate agreement. We will own all rights (including copyright) throughout the world in perpetuity in the Recordings including the right to: (a) broadcast and/or communicate the Recordings to the public via television broadcast (both during the Performances and from the Recordings); (b) communicate the Recordings over the Internet; (c) communicate the Recordings to the public on radio (both for simulcast with the Performances and for simulcast with any later broadcast or transmission of the Recordings); (d) communicate the Recordings via screens around the venue (if applicable); (e) include the Recordings or excerpts from the Recordings on a video, CD, DVD or in other promotional material related to Make Music New York; and (f) synchronize the Recordings with any media for any purpose set out in this paragraph. You will receive no additional payment for the uses of the Recordings. You acknowledge that we have the right to use your name, professional name, photographs, image, likeness and biography for any purposes connected with Make Music New York.</p>
<p align="left">6. To the extent permitted by law, we expressly exclude all express or implied terms, conditions, warranties, statements, assurances and representations in relation to Make Music New York. If any of the exclusions or limitations set out in these terms are declared illegal or void or if you claim that there has been a breach of a term, condition, warranty, statement or assurance which cannot be excluded by these terms, to the extent permitted by law, our entire liability and your exclusive remedy is limited, at our discretion, to us supplying our services again. Nothing in this agreement excludes, restricts or modifies any condition, warranty, right or remedy implied or imposed by statute or regulation if it cannot lawfully be excluded, restricted or modified.</p>
<p align="left">7. We have no involvement in the running or production of any event taking place during Make Music New York (Event). Accordingly we do not accept any responsibility: (a) if any Event is not capable of running as planned; (b) if any Event is cancelled or suspended; (c) for any problems or technical malfunction associated with any Event; (d) if your services are cancelled or suspended; or (e) for any injury, loss or damage incurred or caused by you in connection with your participation in Make Music New York or an Event.</p>
<p align="left">8. To the extent permitted by law, in no event shall we be liable for, and you release us from any claim for, any direct, indirect, incidental, special, exemplary, or consequential damages however arising and on any theory of liability, including without limitation, contract or tort (including negligence or otherwise) in connection with your participation in Make Music New York even if we were aware of the possibility of such damage or if such damage was foreseeable.</p>
<p align="left">9. You undertake and agree to indemnify us and keep us fully indemnified against all actions, suits, claims or demands, costs or expenses (including any and all of our legal fees on an indemnity basis) arising from or relating to: (a) any breach of these terms or any express or implied warranty or representation by you; (b) any claim by any person arising out of the provision of your services; and (c) any damage, injury or loss caused by or resulting from any willful act or negligence by you.</p>
<p align="left">10. You agree that you will be liable for any loss or damage caused by you to any property of any Make Music New York venue, us or any musician, performer, employee, agent or contractor of any Make Music New York venue or for any unlawful or negligent act or omission by you.</p> 
<p align="left">11. This Agreement is subject to the laws of the State of New York and the parties submit to the exclusive jurisdiction of the courts of that State.</p>
<p align="left">12. If any of these terms are found by any court or other competent authority to be illegal, unlawful or unenforceable, then the remainder of these terms shall continue to be valid and enforceable to the fullest extent permitted by law.</p>
<p align="left">13. Any changes to these terms will be posted on the Make Music New York website at <a href="http://www.makemusicny.org">www.makemusicny.org</a>. You will be bound by the version in existence at the time you initially agree.</p></small>
</body>
-->